config/routes.rb
Rails.application.routes.draw do
  	resources :notes do
  	 	resources :versions, only: [:destroy] do
	    	member do	      		
	      		patch :rollback, to: 'versions#rollback'
	    	end
	  	end
  	end

  	root :to => "notes#index"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
	has_paper_trail
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]

  # GET /notes
  # GET /notes.json
  def index
    @notes = Note.all
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:description)
    end
end

app/controllers/versions_controller.rb
class VersionsController < ApplicationController
	
	before_action :set_document_and_version, only: [:rollback]

    def rollback
	    # change the current document to the specified version
	    # reify gives you the object of this version
	    note = @version.reify	    
	    if note.blank?
	    	redirect_to notes_path
	    else
	    	note.save! 
	    	redirect_to edit_note_path(note)
	    end
	end

	private

	    def set_document_and_version
	      @note = Note.find(params[:note_id])
	      @version = @note.versions.find(params[:id])
	    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NoteTask</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/notes/_form.html.erb
<div style="width:500px; margin:auto">
<%= form_for(note) do |f| %>
  <% if note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% note.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= f.text_area :description, :cols=> 40, :rows => 5 %>
  </div>
  <div class="actions">
    <%= f.submit 'Save', :class=>'btn btn-primary'%>
  </div>
<% end %>
</div>

app/views/notes/_note.html.erb
<tr>
  <td><%= note.description %></td>
  <td><%= link_to 'Show', note_path(note)%> | <%= link_to 'Edit', edit_note_path(note)%> |
  <%= link_to 'Remove', note_path(note), :method => 'delete', :data => {:confirm => 'Are you sure you want to delete this note?'}, :class=>'remove' %></td>
</tr>

app/views/notes/_versions.html.erb
<div style="width:500px; margin:auto">

<h4>Previous Versions</h4>

<table style="width:400px; margin:auto" cellspacing="0"  class="table table-striped table-condensed table-responsive">
  <thead>
    <tr>
      <th>Date</th>   
      <th></th>
    </tr>
  </thead>

  <tbody>
    <%- @note.versions.reverse.each do |version| %>
      <tr>
        <td><%= version.created_at %></td>        
        <td><%= link_to 'Rollback', rollback_note_version_path(@note, version), method: 'PATCH'  %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/notes/edit.html.erb
<h1>Editing Note</h1>

<%= render 'form', note: @note %>

<%= link_to 'Show', @note %> |
<%= link_to 'Back', notes_path %>

app/views/notes/index.html.erb
<div style="width:600px; margin:auto">
<p id="notice"><%= notice %></p>

<h1>Notes</h1>

<table cellspacing="0" id="categories_table" class="table table-striped table-condensed table-responsive">
  

  <tbody>
    <% @notes.each do |note| %>
      <%= render note %>
    <% end unless @notes.blank? %>
  </tbody>
</table>

<br>

<%= link_to 'New Note', new_note_path, :class=>'btn btn-primary' %>
</div>

app/views/notes/new.html.erb
<div style="width: 600px; margin: auto">
<h1>New Note</h1>

<%= render 'form', note: @note %>

<%= link_to 'Back', notes_path %>
</div>

app/views/notes/show.html.erb
<div style="width:500px; margin:auto">
	<p id="notice"><%= notice %></p>
	<div>
		<h2><%= @note.description %></h2>
		<%= render "versions"%>
	</div>
	<div>
		<%= link_to 'Edit', edit_note_path(@note) %> |
		<%= link_to 'Back', notes_path %>
	</div>
</div>